apiVersion: v1
kind: Service
metadata:
  name: service-deployer
  labels:
    app: service-deployer
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: service-deployer
  type: LoadBalancer
