apiVersion: v1
kind: Service
metadata:
  name: aem-author-dev
  labels:
    app: aem-author-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4502
  selector:
    app: aem
    runmode: author
    deployment: dev
  type: LoadBalancer
